First_app/urls.py
from django.conf.urls import url
from django.urls import path
from First_app import views

app_name="First_app"

urlpatterns = [
    path('',views.index,name="index" ),
    path('form/',views.form,name="form" ),
    path('form2/',views.form2,name="form2" ),
    path('index2/',views.index2,name="index2" ),
    path('add_album/',views.album_form,name="album_form" ),
    path('add_musician/',views.musician_form,name="musician_form" ),
    path('album_list/<int:artistId>',views.album_list,name="album_list" ),
    path('edit_artist/<int:artist_id>',views.edit_artist,name="edit_artist" ),
    path('edit_album/<int:album_id>',views.edit_album,name="edit_album" ),
    path('delete_album/<int:albumId>',views.delete_album,name="delete_album" ),




]

My_First_Project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('First_app/', include('First_app.urls')),

]

First_app/models.py
from django.db import models

# Create your models here.

class Musician (models.Model):
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    instrument=models.CharField(max_length=50)

    def __str__(self):
        return self.first_name+" "+self.last_name


class Album(models.Model):
    artist=models.ForeignKey(Musician, on_delete=models.CASCADE)
    name=models.CharField(max_length=50)
    release_date=models.DateField()

    rating=(
    (1,"Worst"),
    (2,"Bad"),
    (3,"Not Bad"),
    (4,"Good"),
    (5,"Excellent"),

    )
    num_stars=models.IntegerField(choices=rating)
    def __str__(self):
        return self.name+" Rating: "+str(self.num_stars)

First_app/forms.py
from django import forms
from django.core import validators 
from First_app import models



class user_form(forms.Form):
    user_name=forms.CharField(validators=[validators.MaxLengthValidator(20)],label="Full name",widget=forms.TextInput(attrs={'placeholder':'Enter your full name','style':'width:300px'}))
    user_dob=forms.DateField(label="Date of Birth",widget=forms.TextInput(attrs={'type':'date'}))

    user_email=forms.EmailField()
    user_vemail=forms.EmailField()
    number_field=forms.IntegerField()
    choose=(('A','A'),('B','B'),('C','C'))
    boolean_field=forms.BooleanField()
    dropdown_Menu=forms.ChoiceField(choices=choose)
    radio_button=forms.ChoiceField(choices=choose, widget=forms.RadioSelect)

  # select multiple value in checkbox,radio button and dropdown_Menu

    dropdown_Menu_multiple=forms.MultipleChoiceField(choices=choose)
    checkbox_multiple=forms.MultipleChoiceField(choices=choose, widget=forms.CheckboxSelectMultiple)

    def clean(self):
        all_data=super().clean()
        email=all_data['user_email']
        vemail=all_data['user_vemail']

        if email!=vemail:
            raise forms.ValidationError("Email don't match")





class MusicianForm(forms.ModelForm):
    class Meta:
        model=models.Musician
        fields="__all__"


class AlbumForm(forms.ModelForm):
    release_date=forms.DateField(label="Date of release",widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model=models.Album
        fields="__all__"

First_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from First_app.models import Musician,Album
from First_app import forms
from django.db.models import Avg

# Create your views here.
def index(request):
    musician_list=Musician.objects.order_by('first_name')

    diction={'text1':'This is a list of musician', 'musician':musician_list}
    return render(request,'First_app/index.html',context=diction)


def form(request):
    new_form=forms.user_form()
    diction={'test_form':new_form, 'heading':'This form is created using django library'}

    if request.method=='POST':
        new_form=forms.user_form(request.POST)
        diction.update({'test_form':new_form})

        if new_form.is_valid():
            u_name=new_form.cleaned_data['user_name']
            u_dob=new_form.cleaned_data['user_dob']
            u_email=new_form.cleaned_data['user_email']
            b_field=new_form.cleaned_data['boolean_field']
            d_menu=new_form.cleaned_data['dropdown_Menu']
            r_button=new_form.cleaned_data['radio_button']
            d_menu_multiple=new_form.cleaned_data['dropdown_Menu_multiple']
            c_multiple=new_form.cleaned_data['checkbox_multiple']

            diction.update({'uname':u_name})
            diction.update({'udob':u_dob})
            diction.update({'uemail':u_email})
            diction.update({'form_submitted':'yes'})
            diction.update({'bfield':b_field})
            diction.update({'dmenu':d_menu})
            diction.update({'rbutton':r_button})
            diction.update({'dmenuMultiple':d_menu_multiple})
            diction.update({'cmultiple':c_multiple})




    return render(request,'First_app/form.html',context=diction)



def form2(request):
    new_form=forms.MusicianForm()
    if request.method=='POST':
        new_form=forms.MusicianForm(request.POST)


        if new_form.is_valid():
            new_form.save(commit=True)
            return index(request) #After submit form redirect in index.html page
    diction={'test_form':new_form, 'heading':'This form is created using django library'}
    return render(request,'First_app/form2.html',context=diction)




def index2(request):
    musician_list=Musician.objects.order_by('first_name')
    diction={'title':"Home page","musician_list":musician_list}
    return render(request,'First_app/index2.html',context=diction)

def album_list(request, artistId):
    artist_info=Musician.objects.get(pk=artistId)
    album_list=Album.objects.filter(artist=artistId).order_by('name','release_date')
    artist_rating=Album.objects.filter(artist=artistId).aggregate(Avg('num_stars'))
    diction={'title':"List of albums", 'artist_info':artist_info, 'album_list':album_list,'artist_rating':artist_rating}
    return render(request,'First_app/album_list.html',context=diction)

def musician_form(request):
    form=forms.MusicianForm()

    if request.method=="POST":
        form=forms.MusicianForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index2(request)


    diction={'title':"Add musician" ,"musician_form":form}
    return render(request,'First_app/musician_form.html',context=diction)

def album_form(request):
    form=forms.AlbumForm()

    if request.method=="POST":
        form=forms.AlbumForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index2(request)
    diction={'title':"Add album","album_form":form}
    return render(request,'First_app/album_form.html',context=diction)


def edit_artist(request,artist_id):
    artist_info=Musician.objects.get(pk=artist_id)
    form=forms.MusicianForm(instance=artist_info)
    if request.method=="POST":
        form=forms.MusicianForm(request.POST,instance=artist_info)

        if form.is_valid():
            form.save(commit=True)
            return album_list(request,artist_id)
    diction={'edit_form':form}
    return render(request,'First_app/edit_artist.html',context=diction)


def edit_album(request,album_id):
    album_info=Album.objects.get(pk=album_id)
    form=forms.AlbumForm(instance=album_info)
    if request.method=="POST":
        form=forms.AlbumForm(request.POST,instance=album_info)

        if form.is_valid():
            form.save(commit=True)
            return album_list(request,album_id)
    diction={'edit_form':form}
    diction.update({'album_id':album_id})
    return render(request,'First_app/edit_album.html',context=diction)

def delete_album(request,albumId):
    album_del=Album.objects.get(pk=albumId).delete()
    diction={'delete_msg':'delete album successfully'}


    return render(request,'First_app/delete_album.html',context=diction)

templates/First_app/album_form.html
{% extends 'First_app/base2.html'%}

{% block body_block%}
<h1>album_form page</h1>
<form  method="post">
{{  album_form.as_p }}
{% csrf_token %}
<input type="submit" name="submit" value="submit">

</form>
{% endblock %}

templates/First_app/album_list.html
{% extends 'First_app/base2.html'%}

{% block body_block%}
<h4>Artist Rating: {{artist_rating.num_stars__avg}}</h4>
<h4>List of album</h4>
<h4>Name: {{artist_info.first_name}} {{artist_info.last_name}}</h4>
<h4>Instrument: {{artist_info.instrument}}</h4>
<a href="{% url 'First_app:edit_artist' artist_id=artist_info.id %}" class="btn btn-primary btn-sm">Edit</a>
<h4>List of album</h4>
<table class="table table-bordered">
  <tr>
    <th>Album Name</th>
    <th>Release Date</th>
    <th>Rating</th>
    <th>Action</th>
  </tr>
  {% for album in album_list %}
   <tr>
     <td>{{album.name}}</td>
     <td>{{album.release_date}}</td>
     <td>{{album.num_stars}}</td>
     <td><a href="{% url 'First_app:edit_album' album_id=album.id %}" class="btn btn-success btn-sm">Edit</a>
     <br>
     <br>
     <a href="{% url 'First_app:delete_album' albumId=album.id %}" class="btn btn-danger btn-sm" onclick="return confirm('Are u sure delete this info..')">Delete</a>
     </td>


   </tr>
  {% endfor %}

</table>
{% endblock %}

templates/First_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/First_app/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/First_app/form">Form</a>
      </li>

    </ul>
  </div>
</nav>

{% block body_block %}

{% endblock %}

  </body>
</html>

templates/First_app/base2.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'First_app:index2' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'First_app:musician_form' %}">Add Musician</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'First_app:album_form' %}">Add Album</a>
      </li>

    </ul>
  </div>
</nav>

{% block body_block %}

{% endblock %}

  </body>
</html>

templates/First_app/delete_album.html
{% extends 'First_app/base2.html'%}

{% block body_block%}
<div class="alert alert-danger">
  {{delete_msg}}
</div>
{{aldel}}

{% endblock %}

templates/First_app/edit_album.html
{% extends 'First_app/base2.html'%}

{% block body_block%}
<h4>Edit Album</h4>
<form class="" action="" method="POST">
  {{edit_form.as_p}}
  {% csrf_token %}
  <input type="submit" name="edit" value="Edit">
</form>
<br>

{% endblock %}

templates/First_app/edit_artist.html
{% extends 'First_app/base2.html'%}

{% block body_block%}
<h4>Edit artist</h4>
<form class="" action="" method="POST">
  {{edit_form.as_p}}
  {% csrf_token %}
  <input type="submit" name="submit" value="Update">
</form>
{% endblock %}

templates/First_app/form.html
{% extends "First_app/base.html" %}
{% block body_block %}
    <h1>This is a html form</h1>
    <form class="" action="" method="post">
      <label for="uname">User Name:</label>
      <input type="text" name="uname" value="" required>
      <label for="uemail">User Email:</label>
      <input type="text" name="uemail" value="" required>
      <input type="submit" name="submit2" value="Submit">
    </form>
    <br>
     <hr><hr>
     <form  action="" method="POST">
       <h1>{{heading}}</h1>
       {{test_form.as_p}}
       {% csrf_token %}
         <input type="submit" name="submit" value="Submit">
     </form>
    <hr>
     {% if form_submitted %}
     <p>Name: {{uname}}</p>
     <p>DOB: {{udob}}</p>
     <p>Email: {{uemail}}</p>

     <p>Boolean Field Value:{{bfield}}</p>
     <p>Dropdown Menu Value: {{dmenu}}</p>
     <p>Radio Button Value: {{rbutton}}</p>
     <p>Dropdown Menu MultipleValue: {{dmenuMultiple}}</p>
     <p>Checkbox MultipleValue:{{cmultiple}}</p>

     {% endif %}

     {% endblock %}

templates/First_app/form2.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>form</title>
  </head>
  <body>
  
     <form  action="" method="POST">
       <h1>{{heading}}</h1>
       {{test_form.as_p}}
       {% csrf_token %}
         <input type="submit" name="submit" value="Submit">
     </form>
    <hr>


  </body>
</html>

templates/First_app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Musician list</title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
  </head>
  <body>

    <a href="/First_app/form2/">Add new Musician</a><br>
    <h1>  {{text1}}</h1>

  <br>

  <table border="2">
    <tr>
      <th>First name</th>
      <th>Last Name</th>
      <th>Instruement</th>
    </tr>
    {% for row in musician %}

     <tr>
       <td>{{row.first_name}}</td>
       <td>{{row.last_name}}</td>
       <td>{{row.instrument}}</td>
     </tr>
    {% endfor %}
  </table>
  </body>
</html>

templates/First_app/index2.html
{% extends 'First_app/base2.html'%}

{% block body_block%}
<h1>index2 page</h1>
<h1>Musician list</h1>
{% if musician_list %}
{% for musician in musician_list %}
<li><a href="{% url 'First_app:album_list' artistId=musician.id %}">{{musician.first_name}} {{musician.last_name}}</a></li>

{% endfor %}
{% else %}
<h1>There is no musician</h1>
{% endif %}
{% endblock %}

templates/First_app/musician_form.html
{% extends 'First_app/base2.html'%}

{% block body_block%}
<h1>musician_form page</h1>
<form  method="post">
{{  musician_form.as_p }}
{% csrf_token %}
<input type="submit" name="submit" value="submit">

</form>
{% endblock %}